/* eslint-disable */
// @flow

const masterData = {
  id: 30,
  userId: 30,
  username: 'Елена Трепышина',
  phone: '+79613045087',
  email: 'awesome@test.ru',
  MasterType: 1,
  masterCity: 'Москва',
  isSalon: true,
  salonName: 'Пилки',
  status: 1,
  isVerified: true, // TODO: if it the same with status === 1
  masterPhoto: [
    'http://nadezhdaivera.ru/wp-content/uploads/2012/10/master-manikyura-nordos.png',
    'http://www.pro-rubin.ru/wp-content/uploads/2016/10/51.jpg',
  ],
  workPhoto: [
    'https://besplatka.ua/aws/8/40/47/79/9f2e6a42413e.jpg',
    'http://fashionstylist.kupivip.ru/sites/fashion-kupivip/files/styles/step_full/public/main-16399-f7a7cef06f1fdec5eafacd10f923267e.jpg',
    'http://aqualife21.ru/wp-content/uploads/2015/01/master_nogt_servisa.jpg',
    'https://bizhint.net/wp-content/uploads/2016/12/pokraska-nogtey-lakom.jpg',
    'http://static.wixstatic.com/media/5c07a0_c065cc80ca1245d39896ec954da769e5.jpg',
  ],
  has_certificates: false,
  certificates: null,
  about: null,
  vkProfile: 'https://vk.com/bsops',
  inProfile: 'https://www.instagram.com/heledirn/',
  fbProfile: null,
  okProfile: null,
  site_url: null,
  rating: null,
  sterialization: [
    { title: 'Ультразвук' },
    { title: 'Ультразвук' },
    { title: 'Ультразвук' },
    { title: 'Ультразвук' },
    { title: 'Ультразвук' },
    { title: 'Ультразвук' },
  ],
  services: [
    {
      id: 3,
      masterId: 1,
      serviceId: 3,
      price: 800,
      duration: '30',
    },
    {
      id: 5,
      masterId: 1,
      serviceId: 5,
      price: 950,
      duration: '40',
    },
    {
      id: 13,
      masterId: 1,
      serviceId: 13,
      price: 1000,
      duration: '35',
    },
    {
      id: 35,
      masterId: 1,
      serviceId: 35,
      price: 1100,
      duration: '50',
    },
    {
      id: 41,
      masterId: 1,
      serviceId: 41,
      price: 1200,
      duration: '60',
    },
    {
      id: 47,
      masterId: 1,
      serviceId: 47,
      price: 1250,
      duration: '55',
    },
  ],
  addresses: [
    {
      id: 17,
      masterId: 30,
      city: 'Москва',
      district: 'Головинский',
      street: '1-ый Лихачевский переулок',
      house: '4',
      building: '3',
      subwayStation: 'Водный стадион',
      salonTitle: 'У Вики дома',
      dopInfo: '',
      masterSchedules: [
        {
          id: 933,
          masterId: 30,
          masterAddressId: 17,
          date: '2017-05-27',
          timeStart: '13:30',
          timeEnd: '21:20',
        },
        {
          id: 934,
          masterId: 30,
          masterAddressId: 17,
          date: '2017-05-28',
          timeStart: '10:00',
          timeEnd: '13:40',
        },
        {
          id: 935,
          masterId: 30,
          masterAddressId: 17,
          date: '2017-05-29',
          timeStart: '15:00',
          timeEnd: '22:10',
        },
      ],
      latlng: { latitude: 60.000316, longitude: 30.256373 },
    },
    {
      id: 18,
      masterId: 30,
      city: 'Москва',
      district: 'Головинский',
      street: '2-ой Лихачевский переулок',
      house: '5',
      building: '4',
      subwayStation: 'Подводный стадион',
      salonTitle: 'У Миши дома',
      dopInfo: '',
      masterSchedules: [
        {
          id: 936,
          masterId: 30,
          masterAddressId: 17,
          date: '2017-05-27',
          timeStart: '13:30',
          timeEnd: '21:20',
        },
        {
          id: 937,
          masterId: 30,
          masterAddressId: 17,
          date: '2017-05-28',
          timeStart: '10:00',
          timeEnd: '13:40',
        },
        {
          id: 935,
          masterId: 30,
          masterAddressId: 18,
          date: '2017-05-29',
          timeStart: '15:00',
          timeEnd: '22:10',
        },
      ],
      latlng: { latitude: 60.000316, longitude: 30.256373 },
    },
    {
      id: 19,
      masterId: 30,
      city: 'Москва',
      district: 'Головинский',
      street: '3-ой Лихачевский переулок',
      house: '1',
      building: '2',
      subwayStation: 'Надводный стадион',
      salonTitle: 'У Гриши дома',
      dopInfo: '',
      masterSchedules: [
        {
          id: 936,
          masterId: 30,
          masterAddressId: 17,
          date: '2017-06-27',
          timeStart: '13:30',
          timeEnd: '21:20',
        },
        {
          id: 937,
          masterId: 30,
          masterAddressId: 17,
          date: '2017-06-28',
          timeStart: '10:00',
          timeEnd: '13:40',
        },
        {
          id: 935,
          masterId: 30,
          masterAddressId: 18,
          date: '2017-06-29',
          timeStart: '15:00',
          timeEnd: '22:10',
        },
      ],
      latlng: { latitude: 60.000316, longitude: 30.256373 },
    },
  ],
};

export const equipmentInfo = [
  'Ультразвук, Ультрафиолет, Дезинфекция раствором спиртом устраняет грибковую и бактериальную флору',
  'Гласперленовый стерилизатор',
  'Стерилизация в специальном аппарате под воздействием высокой температуры',
];

export default masterData;
