export default {
  ACTIVITY_INDICATOR_ANIMATING: 'ACTIVITY_INDICATOR_ANIMATING',
  DICTIONARIES_CATEGORY_SERVICES_SET: 'DICTIONARIES_CATEGORY_SERVICES_SET',
  DICTIONARIES_SERVICES_SET: 'DICTIONARIES_SERVICES_SET',
};
