export default {
  ACTIVITY_INDICATOR_ANIMATING: 'ACTIVITY_INDICATOR_ANIMATING',
  DICTIONARIES_CATEGORY_SERVICES_SET: 'DICTIONARIES_CATEGORY_SERVICES_SET',
  DICTIONARIES_SERVICES_SET: 'DICTIONARIES_SERVICES_SET',
  GEO_CITIES_SET: 'GEO_CITIES_SET',
  GEO_DATA_CLEAR: 'GEO_DATA_CLEAR',
  GEO_DATA_SET: 'GEO_DATA_SET',
  GEO_PLACE_SET: 'GEO_PLACE_SET',
  GEO_SUBWAY_STATIONS_SET: 'GEO_SUBWAY_STATIONS_SET',
  USER_LOCATION_SET: 'USER_LOCATION_SET',
};
