export default {
  MASTER_CALENDAR_SET_INTERVAL: 'MASTER_CALENDAR_SET_INTERVAL',
  MASTER_CALENDAR_SET_PARAM: 'MASTER_CALENDAR_SET_PARAM',
  MASTER_CALENDAR_SET_RECIPIENT_DATE: 'MASTER_CALENDAR_SET_RECIPIENT_DATE',
  MASTER_FIELD_SET_PARAM: 'MASTER_FIELD_SET_PARAM',
  MASTER_FIELD_SET_VALUE: 'MASTER_FIELD_SET_VALUE',
  MASTER_PHOTO_REMOVE: 'MASTER_PHOTO_REMOVE',
  MASTER_PHOTO_SET: 'MASTER_PHOTO_SET',
  MASTER_PHOTO_SET_MOCK: 'MASTER_PHOTO_SET_MOCK',
  MASTER_SERVICE_SET_PARAM: 'MASTER_SERVICE_SET_PARAM',
  MASTER_SERVICE_TOOGLE: 'MASTER_SERVICE_TOOGLE',
};
