export default {
    MASTER_EDIT_CALENDARS_SET: 'MASTER_EDIT_CALENDARS_SET',
    MASTER_EDIT_GENERAL_INFO_SET: 'MASTER_EDIT_GENERAL_INFO_SET',
    MASTER_EDIT_HANDLING_TOOLS_SET: 'MASTER_EDIT_HANDLING_TOOLS_SET',
    MASTER_EDIT_MANICURE_SERVICES_SET: 'MASTER_EDIT_MANICURE_SERVICES_SET',
    MASTER_EDIT_PEDICURE_SERVICES_SET: 'MASTER_EDIT_PEDICURE_SERVICES_SET',
};
