export default {
  MASTER_PHOTO_SET: 'MASTER_PHOTO_SET',
  MASTER_PHOTO_SET_MOCK: 'MASTER_PHOTO_SET_MOCK',
  MASTER_PHOTO_REMOVE: 'MASTER_PHOTO_REMOVE',
  MASTER_FIELD_SET_VALUE: 'MASTER_FIELD_SET_VALUE',
  MASTER_FIELD_SET_PARAM: 'MASTER_FIELD_SET_PARAM',
  MASTER_ITEM_SET_ACTIVE: 'MASTER_ITEM_SET_ACTIVE',
  MASTER_CUSTOM_DATE_PUSH: 'MASTER_CUSTOM_DATE_PUSH',
};
