export default {
  PROFILE_ADDRESSES_SET: 'PROFILE_ADDRESSES_SET',
  PROFILE_DATA_SET: 'PROFILE_DATA_SET',
  PROFILE_MAIN_SET: 'PROFILE_MAIN_SET',
  PROFILE_MASTER_SERVICES_SET: 'PROFILE_MASTER_SERVICES_SET',
};
