export default {
  SEARCH_TOOGLE_SERVICE: 'SEARCH_TOOGLE_SERVICE',
  SEARCH_SET_MASTER_TYPE: 'SEARCH_SET_MASTER_TYPE',
  SEARCH_SET_DAY: 'SEARCH_SET_DAY',
  SEARCH_ADDRESSES_SET: 'SEARCH_ADDRESSES_SET',
  SEARCH_ADDRESSES_RESET: 'SEARCH_ADDRESSES_RESET',
  SEARCH_DEPARTURE_TOGGLE: 'SEARCH_DEPARTURE_TOGGLE'
};
