export default {
  SEARCH_CITY_ADD: 'SEARCH_CITY_ADD',
  SEARCH_DEPARTURE_TOGGLE: 'SEARCH_DEPARTURE_TOGGLE',
  SEARCH_ITEMS_RESET: 'SEARCH_ITEMS_RESET',
  SEARCH_ITEMS_SET: 'SEARCH_ITEMS_SET',
  SEARCH_SET_DAY: 'SEARCH_SET_DAY',
  SEARCH_SET_MASTER_TYPE: 'SEARCH_SET_MASTER_TYPE',
  SEARCH_TOOGLE_EXTENSION: 'SEARCH_TOOGLE_EXTENSION',
  SEARCH_TOOGLE_SERVICE: 'SEARCH_TOOGLE_SERVICE',
  SEARCH_TOOGLE_WITHDRAWAL: 'SEARCH_TOOGLE_WITHDRAWAL',
};
