export default {
  SEARCH_ADDRESSES_ITEMS_SET: 'SEARCH_ITEMS_SET',
  SEARCH_CITY_ADD: 'SEARCH_CITY_ADD',
  SEARCH_DEPARTURE_TOGGLE: 'SEARCH_DEPARTURE_TOGGLE',
  SEARCH_ITEMS_RESET: 'SEARCH_ITEMS_RESET',
  SEARCH_MASTERS_ITEMS_SET: 'SEARCH_MASTERS_ITEMS_SET',
  SEARCH_SET_DAY: 'SEARCH_SET_DAY',
  SEARCH_SET_MASTER_TYPE: 'SEARCH_SET_MASTER_TYPE',
  SEARCH_TOGGLE_EXTENSION: 'SEARCH_TOGGLE_EXTENSION',
  SEARCH_TOGGLE_SERVICE: 'SEARCH_TOGGLE_SERVICE',
  SEARCH_TOGGLE_WITHDRAWAL: 'SEARCH_TOGGLE_WITHDRAWAL',
};
