platform :ios, '8.0'

inhibit_all_warnings!

NODE_MODULES_PATH = '../node_modules'

target 'relak' do

  pod 'GoogleMaps', '~> 2.5.0'
  pod 'react-native-google-analytics-bridge', :path => File.join(NODE_MODULES_PATH, 'react-native-google-analytics-bridge')
  pod 'react-native-google-maps', :path => File.join(NODE_MODULES_PATH, 'react-native-maps')
  pod 'react-native-image-picker', :path => File.join(NODE_MODULES_PATH, 'react-native-image-picker')
  pod 'react-native-maps', :path => File.join(NODE_MODULES_PATH, 'react-native-maps')
  pod 'react-native-fetch-blob', :path => File.join(NODE_MODULES_PATH, 'react-native-fetch-blob')
  pod 'ReactNativeFabric', :path => File.join(NODE_MODULES_PATH, 'react-native-fabric')
  pod 'BVLinearGradient', :path => File.join(NODE_MODULES_PATH, 'react-native-linear-gradient')
  pod 'SentryReactNative', :path => File.join(NODE_MODULES_PATH, 'react-native-sentry')
  pod 'yoga', :path => File.join(NODE_MODULES_PATH, 'react-native/ReactCommon/yoga')
  pod 'React', :path => File.join(NODE_MODULES_PATH, 'react-native'), :subspecs => [
    'Core',
    'DevSupport',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTVibration',
    'BatchedBridge',
  ]
end
